# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Zishan Ahmad's Blog
tagline:          ''
description:      ''
url:              http://zishanahmad.github.io/blog/
baseurl:          /blog/

author:
  name:           'Zishan Ahmad'
  url:            https://twitter.com/ahmad_zishan

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/zishanAhmad
